yarnPath: .yarn/releases/yarn-3.2.0-rc.3.cjs
pnpMode: "loose"
packageExtensions:
  "node-fetch@2.6.1":
    dependencies:
      "encoding": "*"
  "@types/react@17.0.34":
    dependencies:
      "prop-types": "*"
  "debug@*":
    dependencies:
      "supports-color": "*"
pnpEnableEsmLoader: true
